version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
    environment:
      - PYTHONUNBUFFERED=1
      - AZURE_STORAGE_CONNECTION_STRING=${AZURE_STORAGE_CONNECTION_STRING}
  frontend:
    build: ./react-app
    ports:
      - "5173:4173"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:8000
  redis:
    image: redis:7
    ports:
      - "6379:6379"